png("plot4.png", width = 480, height = 480)
par(mfrow=c(2,2),mar=c(4,4,2,1), oma=c(0,0,2,0))
plot(b$DateTime, b$Global_active_power,type = "l", ylab="Global Active Power (kilowatts)", xlab=" ")
plot(b$DateTime, b$Voltage, xlab="DateTime", ylab="Voltage",type="l")
plot(b$DateTime,b$Sub_metering_1, type="l", ylab="Energy sub metering",xlab=" ")
lines(b$DateTime,b$Sub_metering_2,type="l",col="Blue")
lines(b$DateTime,b$Sub_metering_3,type="l",col="Red")
legend("topright", legend=c("Sub_metering_1","Sub_metering_2", "Sub_metering_3"),y = c(b$Sub_metering_1, b$Sub_metering_2, b$Sub_metering_3),col = c("Black","Red","Blue"), lty=1, x.intersp=0.75,y.intersp=0.75,cex = 0.60)
plot(b$DateTime, b$Global_reactive_power, xlab="DateTime",type="l")
dev.off()